Repository IT-Cotato/10th-Kampus-FE, pull requests merged in 2025-02, with the labels that each got.

#33 [FEAT] 게시글 리스트 보드별 특정 디테일 기능 구현 및 애니메이션 컴포넌트 변경
  src/assets/imgs/activeScrap.svg
  src/assets/imgs/search.svg
  src/assets/imgs/translate.svg
  src/components/board/FilterBox.jsx
  src/components/board/PostList.jsx
  src/components/board/TipsPostList.jsx
  src/components/common/StateChangeAnimate.jsx
  src/pages/board/allboard.jsx
  src/pages/board/board.jsx
  tailwind.config.js
Labels: ✨ Feature, 🔨 Fix, 🕶️ Style

#34 [FEAT] 계정 삭제 페이지 구현
  src/components/common/MainButton.jsx
  src/components/common/inputRadio.jsx
  src/components/common/popup.jsx
  src/components/common/toggle.jsx
  src/components/join/TermsModal.jsx
  src/components/join/searchDropdown.jsx
  src/pages/auth/profileSettings.jsx
  src/pages/auth/terms.jsx
  src/pages/my/etc/deleteAccount.jsx
  src/pages/my/settings/notification.jsx
  tailwind.config.js
Labels: ✨ Feature, 🕶️ Style

#36 [FIX]: 애니메이션 모달 포탈 적용
  index.html
  src/components/common/StateChangeAnimate.jsx
Labels: 🔨 Fix

#49 [FEAT] 검색 기능 구현 및 세부 오류 수정
  package-lock.json
  package.json
  src/assets/imgs/previous.svg
  src/assets/imgs/x.svg
  src/assets/lottie/loading.json
  src/components/board/PostList.jsx
  src/components/common/Loading.jsx
  src/components/common/titleHeader.jsx
  src/components/join/TermsModal.jsx
  src/components/search/RecentSearch.jsx
  src/components/search/SearchBar.jsx
  src/pages/board/allboard.jsx
  src/pages/board/board.jsx
  src/pages/index.js
  src/pages/search/Search.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
  tailwind.config.js
Labels: ✨ Feature, 🔨 Fix, 🕶️ Style

#50 [FEAT] 게시글 작성 페이지 구현
  src/assets/imgs/ImgX.svg
  src/assets/imgs/camera.svg
  src/assets/imgs/pencil.svg
  src/components/board/FilterBox.jsx
  src/components/board/write/SelectCategory.jsx
  src/components/board/write/UploadPics.jsx
  src/components/board/write/WriteButton.jsx
  src/components/board/write/WriteContent.jsx
  src/components/board/write/WriteTitle.jsx
  src/components/common/TranslateButton.jsx
  src/constants/categories.js
  src/pages/board/board.jsx
  src/pages/board/write.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, 🕶️ Style

#53 [FEAT] 마이페이지 Contact Us
  src/components/board/write/WriteContent.jsx
  src/components/board/write/WriteTitle.jsx
  src/components/common/ButtonRound.jsx
  src/components/common/titleHeader.jsx
  src/components/layout/ContactUs.jsx
  src/components/service/faq/faqItem.jsx
  src/components/service/inquiry/inquiryButton.jsx
  src/components/service/inquiry/inquiryEmpty.jsx
  src/components/service/inquiry/inquiryItem.jsx
  src/components/service/inquiry/inquiryList.jsx
  src/components/service/notice.jsx
  src/components/service/notice/NoticeList.jsx
  src/constants/faqs.js
  src/pages/board/write.jsx
  src/pages/my/mypage.jsx
  src/pages/my/service/faq.jsx
  src/pages/my/service/inquiry.jsx
  src/pages/my/service/inquiry/inquiry.jsx
  src/pages/my/service/inquiry/inquiryDetail.jsx
  src/pages/my/service/inquiry/writeInquiry.jsx
  src/pages/my/service/notice.jsx
  src/pages/my/service/service.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, 🕶️ Style

#55 [Feat] 채팅 리스트, 채팅 디테일
  .prettierrc
  .prettierrc.json
  src/assets/imgs/blockIcon.svg
  src/assets/imgs/defaultProfile.svg
  src/assets/imgs/leaveIcon.svg
  src/assets/imgs/send.svg
  src/components/chat/articleInfo.jsx
  src/components/chat/listItem.jsx
  src/components/chat/newMsgCnt.jsx
  src/components/common/noticeBox.jsx
  src/components/common/userInput.jsx
  src/pages/board/board.jsx
  src/pages/chat/chatId.jsx
  src/pages/chat/chatList.jsx
  src/pages/chat/list.jsx
  src/pages/index.js
  src/pages/my/settings/MyInfo.jsx
  src/pages/my/settings/Notification.jsx
  src/pages/my/settings/SchoolVerification.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
  src/utils/touchDrag.js
  tailwind.config.js
Labels: ✨ Feature, 🕶️ Style

#61 [FEAT] Contact Us Notice 상세 페이지
  src/components/service/notice/NoticeList.jsx
  src/pages/index.js
  src/pages/my/service/notice/notice.jsx
  src/pages/my/service/notice/noticeDetail.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, 🕶️ Style

#64 [FIX] notice 페이지 오타 수정
  src/pages/my/service/notice/notice.jsx
Labels: 🐛 Bug, 🔨 Fix

#59 [FEAT] 메인 페이지 UI 구현 (홈)
  src/assets/imgs/kampusLogo.svg
  src/assets/imgs/more.svg
  src/assets/imgs/notification_true.svg
  src/assets/imgs/postCardIcon.svg
  src/components/board/BoardList.jsx
  src/components/board/BoardListBox.jsx
  src/components/home/BoardBox.jsx
  src/components/home/BoardHeader.jsx
  src/components/home/BoxList.jsx
  src/components/layout/navbar.jsx
  src/components/search/SearchBar.jsx
  src/pages/board/allboard.jsx
  src/pages/board/board.jsx
  src/pages/home/home.jsx
  src/routes/AppRouter.jsx
  src/utils/boardTitleUtils.js
Labels: ✨ Feature, 🕶️ Style

#65 [FEAT] Blocking Management 페이지
  src/assets/imgs/disabledLogo.svg
  src/components/block/ChatBlockedList.jsx
  src/components/common/ButtonRound.jsx
  src/components/layout/BlockingManagement.jsx
  src/pages/index.js
  src/pages/my/etc/blockChat.jsx
  src/pages/my/etc/blockSecondhand.jsx
  src/pages/my/etc/blockingManagement.jsx
  src/pages/my/mypage.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, 🕶️ Style

#75 [FEAT] 스플래시 스크린, 로그인 페이지 UI 퍼블리싱
  src/assets/fonts/Roboto-Medium.ttf
  src/assets/imgs/GoogleLogo.svg
  src/assets/imgs/KakaoLogo.svg
  src/assets/imgs/disabledLogo.svg
  src/assets/imgs/kampusLogo.svg
  src/assets/imgs/loginGoogle.svg
  src/assets/imgs/loginKakao.png
  src/components/common/googleLogin.jsx
  src/components/common/kakaoLogin.jsx
  src/pages/SplashScreen.jsx
  src/pages/auth/login.jsx
  src/pages/board/board.jsx
  src/pages/home/home.jsx
  src/pages/home/landingPage.jsx
  src/pages/index.js
  src/pages/my/community/CommunityScrap.jsx
  src/pages/my/community/MyArticles.jsx
  src/pages/my/community/MyComments.jsx
  src/pages/my/etc/blockChat.jsx
  src/routes/AppRouter.jsx
  src/styles/global.css
  tailwind.config.js
Labels: ✨ Feature, ⚙️ Chore, 🎨 Design

#72 [FEAT] 사용자 입력창 컴포넌트, SockJS 설정
  eslint.config.js
  jsconfig.json
  package-lock.json
  package.json
  src/apis/chat/getChatList.api.js
  src/apis/chat/getChatMessages.api.js
  src/apis/chat/websocket.js
  src/components/chat/listItem.jsx
  src/components/common/noticeBox.jsx
  src/components/common/userInput.jsx
  src/constants/api.js
  src/pages/chat/chatList.jsx
  src/pages/chat/chatRoom.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/utils/utcToKst.js
Labels: ✨ Feature, ⚙️ Chore, 🎨 Design

#81 [FEAT] 관리자페이지 초기 레이아웃
  robots.txt
  src/components/layout/Admin.jsx
  src/pages/admin/AdminLogin.jsx
  src/pages/admin/BoardManagement.jsx
  src/pages/admin/CreateCardnews.jsx
  src/pages/admin/Dashboard.jsx
  src/pages/admin/ReportManagement.jsx
  src/pages/admin/SignupManagement.jsx
  src/pages/admin/Statistics.jsx
  src/pages/admin/UserManagement.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, 🎨 Design

#78 [FEAT] 회원 정보 수정 페이지 구현
  src/components/common/DisabledInput.jsx
  src/components/common/titleHeader.jsx
  src/components/join/searchDropdown.jsx
  src/components/join/searchDropdownWithNoLabel.jsx
  src/components/join/usernameInput.jsx
  src/pages/auth/profileSettings.jsx
  src/pages/auth/schoolSearch.jsx
  src/pages/my/etc/blockingManagement.jsx
  src/pages/my/settings/MyInfo.jsx
  src/pages/my/settings/myInfo.jsx
Labels: ✨ Feature, 🎨 Design, ♻️ Refactor

#80 [FEAT] 채팅 모달, report
  src/apis/chat/getChatMessages.api.js
  src/assets/imgs/muteIcon.svg
  src/assets/imgs/replyIcon.svg
  src/components/chat/blockModal.jsx
  src/components/chat/chatMenu.jsx
  src/components/chat/leaveModal.jsx
  src/components/chat/listItem.jsx
  src/components/chat/messageModal.jsx
  src/components/chat/reportModal.jsx
  src/components/chat/roomHeader.jsx
  src/components/common/ButtonRound.jsx
  src/components/common/MenuBar.jsx
  src/components/common/Modal.jsx
  src/components/common/StateChangeAnimate.jsx
  src/components/common/inputRadio.jsx
  src/components/common/userInput.jsx
  src/pages/board/board.jsx
  src/pages/chat/chatList.jsx
  src/pages/chat/chatReport.jsx
  src/pages/chat/chatRoom.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
  src/styles/global.css
Labels: ✨ Feature, 🔨 Fix, 🎨 Design

#83 [FEAT] 관리자페이지 카드뉴스 제작 페이지
  src/App.jsx
  src/assets/imgs/admin/HamburgerIcon.png
  src/components/layout/Admin.jsx
  src/pages/admin/CardnewsList.jsx
  src/pages/admin/CreateCardnews.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Design

#86 [FEAT] 게시글 작성 페이지 디자인 수정
  src/components/board/write/UploadPics.jsx
  src/components/board/write/WriteContent.jsx
  src/components/board/write/WriteTitle.jsx
  src/components/common/MainButton.jsx
  src/components/common/MainWhiteButton.jsx
  src/pages/board/write.jsx
Labels: ✨ Feature, 🔨 Fix, 🎨 Design

#87 [FEAT] 게시글 댓글 및 게시글 메뉴바 기능 UI 구현
  src/components/board/BoardList.jsx
  src/components/board/BoardListBox.jsx
  src/components/board/PostComment.jsx
  src/components/board/PostHeader.jsx
  src/components/board/TipsPostList.jsx
  src/components/common/ImageSlider.jsx
  src/components/common/MenuBar.jsx
  src/components/common/ScarpComponent.jsx
  src/components/common/popup.jsx
  src/components/common/userInput.jsx
  src/components/home/BoxList.jsx
  src/pages/board/board.jsx
  src/pages/board/post.jsx
  src/pages/home/home.jsx
  src/utils/formatTime.js
  vite.config.js
Labels: ✨ Feature, 🕶️ Style, 🎨 Design

#85 [FEAT] 채팅 api, web socket 통신
  package-lock.json
  package.json
  src/apis/auth/login.api.js
  src/apis/chat/chatList.api.js
  src/apis/chat/chatRoom.api.js
  src/apis/chat/getChatList.api.js
  src/apis/chat/getChatMessages.api.js
  src/apis/chat/messages.api.js
  src/apis/chat/websocket.js
  src/components/chat/chatListPage.jsx
  src/components/chat/chatRoomPage.jsx
  src/components/chat/listItem.jsx
  src/constants/api.js
  src/hooks/use-websocket.jsx
  src/pages/chat/chat.jsx
  src/pages/chat/chatList.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, ♻️ Refactor

#92 [FEAT] 관리자페이지 게시판 관리 페이지 구현
  src/components/admin/Dropdown.jsx
  src/components/admin/MenuBar.jsx
  src/components/admin/ShortInput.jsx
  src/components/join/searchDropdown.jsx
  src/components/layout/Admin.jsx
  src/pages/admin/BoardManagement.jsx
  src/pages/admin/CardnewsList.jsx
  src/pages/admin/board/BoardManagement.jsx
  src/pages/admin/board/CreateBoard.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, 🎨 Design

#96 [REFACTOR] 디자인 수정 사항 반영 및 리팩토링
  src/components/board/write/UploadPics.jsx
  src/components/chat/blockModal.jsx
  src/components/chat/leaveModal.jsx
  src/components/common/Alert.jsx
  src/components/common/ButtonRound.jsx
  src/components/common/Modal.jsx
  src/components/common/titleHeader.jsx
  src/components/join/SkipHeader.jsx
  src/components/join/searchDropdown.jsx
  src/components/layout/BlockingManagement.jsx
  src/components/layout/ContactUs.jsx
  src/components/layout/MyArticle.jsx
  src/components/layout/Scrap.jsx
  src/components/layout/layout.jsx
  src/components/layout/navbar.jsx
  src/pages/auth/profileSettings.jsx
  src/pages/auth/schoolEmail.jsx
  src/pages/auth/schoolPhoto.jsx
  src/pages/auth/schoolSearch.jsx
  src/pages/auth/schoolVerification.jsx
  src/pages/auth/terms.jsx
  src/pages/my/community/CommunityScrap.jsx
  src/pages/my/community/MyArticles.jsx
  src/pages/my/community/MyComments.jsx
  src/pages/my/community/SecondhandScrap.jsx
  src/pages/my/community/myArticle.jsx
  src/pages/my/etc/blockSecondhand.jsx
  src/pages/my/etc/deleteAccount.jsx
  src/pages/my/service/inquiry/writeInquiry.jsx
  src/pages/my/settings/MyInfo.jsx
Labels: 🎨 Design, ♻️ Refactor

#94 [FEAT] 게시판, 게시글 리스트 뷰, 게시글 상세보기, 카드 뉴스 리스트 뷰, 게시글 작성 연동
  src/apis/auth/login.api.js
  src/apis/board/getBoardDetail.api.js
  src/apis/board/getBoardList.api.js
  src/apis/board/getPostDetail.api.js
  src/apis/board/getPostList.api.js
  src/apis/board/postWritePost.api.js
  src/apis/board/toggleBoardFavorite.api.js
  src/apis/board/togglePostScrap.api.js
  src/components/board/BoardList.jsx
  src/components/board/PostHeader.jsx
  src/components/board/PostList.jsx
  src/components/board/TipsPostList.jsx
  src/components/board/write/WriteButton.jsx
  src/components/common/FocusImageSlider.jsx
  src/components/common/MenuBar.jsx
  src/components/common/ScrapComponent.jsx
  src/components/common/kakaoLogin.jsx
  src/constants/api.js
  src/main.jsx
  src/pages/board/allboard.jsx
  src/pages/board/board.jsx
  src/pages/board/post.jsx
  src/pages/board/write.jsx
  src/routes/path.ts
  src/utils/formatTime.js
  src/utils/generateApiPath.js
Labels: ✨ Feature, 🕶️ Style, ♻️ Refactor

#91 [FEAT]: 번역 UI 구현
  src/components/board/write/TranslatePopup.jsx
  src/pages/board/write.jsx
Labels: ✨ Feature, 🎨 Design

#100 [FEAT & REFACTOR]: 게시글 신고 페이지 구현 및 계정 삭제 채팅방 신고 리팩토링
  src/components/common/Report.jsx
  src/components/common/inputRadio.jsx
  src/pages/board/postReport.jsx
  src/pages/chat/chatReport.jsx
  src/pages/index.js
  src/pages/my/etc/deleteAccount.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, ♻️ Refactor

#103 [FEAT]: 알림 UI 구현
  src/assets/imgs/commentNoti.svg
  src/assets/imgs/notificationDelete.svg
  src/assets/imgs/trendingNoti.svg
  src/components/notification/NotificationBox.jsx
  src/components/notification/NotificationHeader.jsx
  src/pages/home/home.jsx
  src/pages/index.js
  src/pages/notification/notificationList.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, 🎨 Design

#105 [FEAT] Notice (게시판 가이드) UI 구현
  src/constants/kampusGuide.js
  src/pages/board/board.jsx
  src/pages/boardGuide/boardGuide.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, 🎨 Design

#110 [FEAT] 관리자페이지 카드뉴스 본문 추가, 메뉴 추가
  src/assets/imgs/admin/Board.svg
  src/assets/imgs/admin/Cardnews.svg
  src/assets/imgs/admin/Graph.svg
  src/assets/imgs/admin/Home.svg
  src/assets/imgs/admin/Plus.svg
  src/assets/imgs/admin/Report.svg
  src/assets/imgs/admin/Setting.svg
  src/assets/imgs/admin/User.svg
  src/assets/imgs/admin/Volume.svg
  src/components/layout/Admin.jsx
  src/pages/admin/CardnewsList.jsx
  src/pages/admin/board/BoardManagement.jsx
  src/pages/admin/cardnews/CardnewsList.jsx
  src/pages/admin/cardnews/CreateCardnews.jsx
  src/pages/index.js
Labels: ✨ Feature, 🎨 Design

#113 [FEAT] 관리자페이지 공지사항 구현
  src/components/layout/Admin.jsx
  src/pages/admin/notice/CreateNotice.jsx
  src/pages/admin/notice/NoticeManagement.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, 🎨 Design

#119 [FEAT] 관리자페이지 게시판 연동
  src/apis/admin/deleteAdminBoard.api.js
  src/apis/admin/getAdminBoardDetail.api.js
  src/apis/admin/getAdminBoardList.api.js
  src/apis/admin/postActivateBoard.api.js
  src/apis/admin/postCreateBoard.api.js
  src/apis/admin/postInactivateBoard.api.js
  src/apis/admin/putAdminBoard.api.js
  src/components/join/searchDropdown.jsx
  src/constants/api.js
  src/pages/admin/board/BoardManagement.jsx
  src/pages/admin/board/CreateBoard.jsx
Labels: ✨ Feature

#118 [FEAT] 웹소켓 연동 - 채팅리스트
  public/favicon.svg
  src/apis/chat/chatList.api.js
  src/apis/chat/chatRoom.api.js
  src/apis/chat/messages.api.js
  src/apis/user/userDetail.api.js
  src/components/chat/articleInfo.jsx
  src/components/chat/chatListPage.jsx
  src/components/chat/chatRoomPage.jsx
  src/components/chat/listItem.jsx
  src/components/chat/roomHeader.jsx
  src/components/common/MenuBar.jsx
  src/components/common/userInput.jsx
  src/components/layout/chatLayout.jsx
  src/constants/api.js
  src/hooks/use-websocket.jsx
  src/pages/chat/chat.jsx
  src/routes/AppRouter.jsx
  src/utils/utcToKst.js
Labels: 🐛 Bug, ✨ Feature, 🔨 Fix

#124 [FEAT] 게시글, 댓글, 번역, 카드뉴스 연동
  src/apis/board/getPostList.api.js
  src/apis/board/handlePost.api.js
  src/apis/board/togglePostLike.api.js
  src/apis/comment/addComment.api.js
  src/apis/comment/deleteComment.api.js
  src/apis/comment/getComment.api.js
  src/apis/comment/toggleCommentLike.api.js
  src/apis/translate/translatePost.api.js
  src/apis/translate/translateText.api.js
  src/apis/translate/writePostTranslate.api.js
  src/assets/lottie/translating.json
  src/components/board/PostComment.jsx
  src/components/board/PostHeader.jsx
  src/components/board/PostList.jsx
  src/components/board/TipsPostList.jsx
  src/components/common/MenuBar.jsx
  src/components/common/ScrapComponent.jsx
  src/components/common/Translating.jsx
  src/components/common/titleHeader.jsx
  src/components/common/userInput.jsx
  src/constants/api.js
  src/pages/board/board.jsx
  src/pages/board/post.jsx
  src/pages/board/write.jsx
  src/utils/formatTime.js
Labels: ✨ Feature

#128 [FEAT] 관리자페이지 공지사항, 마이페이지 공지사항 연동
  src/apis/admin/deleteAdminNotice.api.js
  src/apis/admin/patchAdminNotice.api.js
  src/apis/admin/postCreateNotice.api.js
  src/apis/mypage/getNoticeDetail.api.js
  src/apis/mypage/getNoticeList.api.js
  src/components/service/notice/NoticeList.jsx
  src/constants/api.js
  src/pages/admin/notice/CreateNotice.jsx
  src/pages/admin/notice/NoticeManagement.jsx
  src/pages/my/service/notice/notice.jsx
  src/pages/my/service/notice/noticeDetail.jsx
Labels: ✨ Feature

#127 [FEAT] 임시 로그아웃 구현
  src/pages/my/mypage.jsx
Labels: ✨ Feature

#126 [FEAT] 홈 화면 연동
  src/apis/board/getPostList.api.js
  src/apis/home/getFavorite.api.js
  src/apis/home/getTrend.api.js
  src/components/board/PostList.jsx
  src/components/home/BoardBox.jsx
  src/components/home/BoardHeader.jsx
  src/components/home/BoxList.jsx
  src/constants/api.js
  src/pages/board/allboard.jsx
  src/pages/board/board.jsx
  src/pages/home/home.jsx
Labels: ✨ Feature

#130 [FEAT] 마켓 기본 UI 구현
  src/components/common/titleHeader.jsx
  src/components/common/userInput.jsx
  src/pages/index.js
  src/pages/market/market.jsx
  src/routes/AppRouter.jsx
Labels: ⚙️ Chore, 🎨 Design

#131 [FEAT] 학교 인증 연동
  src/apis/auth/getSchoolStatus.api.js
  src/apis/auth/postSchoolEmailCode.api.js
  src/apis/auth/postSchoolPhoto.api.js
  src/components/join/VerificationCodeModal.jsx
  src/constants/api.js
  src/hooks/use-CheckSchoolStatus.js
  src/pages/auth/schoolEmail.jsx
  src/pages/auth/schoolPhoto.jsx
  src/pages/auth/schoolSearch.jsx
  src/pages/auth/schoolVerification.jsx
Labels: ✨ Feature

#135 [FEAT] 관리자페이지 카드뉴스 연동
  src/apis/admin/deleteCardnews.api.js
  src/apis/admin/getAdminCardnewsList.api.js
  src/apis/admin/postCreateCardnews.api.js
  src/constants/api.js
  src/pages/admin/cardnews/CardnewsList.jsx
  src/pages/admin/cardnews/CreateCardnews.jsx
Labels: ✨ Feature

#136 [FEAT] 검색 연동
  src/apis/search/searchDeleteKeyword.api.js
  src/apis/search/searchKeywords.api.js
  src/apis/search/searchTotal.api.js
  src/components/search/RecentSearch.jsx
  src/components/search/SearchBar.jsx
  src/constants/api.js
  src/pages/search/Search.jsx
Labels: ✨ Feature, ⚙️ Chore

#138 [FEAT] 채팅 초기 메시지, unreadcount 에러 해결
  src/components/chat/chatListPage.jsx
  src/components/chat/chatRoomPage.jsx
  src/components/chat/listItem.jsx
  src/components/chat/roomHeader.jsx
  src/constants/faqs.js
  src/hooks/use-websocket.jsx
  src/pages/chat/chat.jsx
Labels: 🐛 Bug, ✨ Feature, 🔨 Fix

#140 [FEAT] 채팅 작성자 댓글 디자인 수정 및 카드 뉴스 작성자 디자인 수정
  src/assets/imgs/kampusPost.svg
  src/components/board/PostComment.jsx
  src/components/board/PostHeader.jsx
  src/pages/board/post.jsx
Labels: ⚙️ Chore, 🎨 Design

#139 [FIX] 채팅 리스트 에러, 삭제 기능 추가
  src/apis/chat/chatList.api.js
  src/apis/chat/messages.api.js
  src/components/chat/chatListPage.jsx
  src/components/chat/chatRoomPage.jsx
  src/components/chat/listItem.jsx
  src/constants/api.js
  src/hooks/use-websocket.jsx
  src/pages/chat/chat.jsx
Labels: ✨ Feature, 🔨 Fix

#142 [FEAT] 마이페이지 문의사항 연동
  src/apis/mypage/getInquiryDetail.api.js
  src/apis/mypage/getInquiryList.api.js
  src/apis/mypage/postWriteInquiry.api.js
  src/constants/api.js
  src/pages/my/service/inquiry/inquiry.jsx
  src/pages/my/service/inquiry/inquiryDetail.jsx
  src/pages/my/service/inquiry/writeInquiry.jsx
Labels: ✨ Feature

#143 [FEAT] 채팅 읽음 처리, 관리자 이름
  src/components/chat/chatRoomPage.jsx
  src/components/layout/Admin.jsx
  src/hooks/use-websocket.jsx
  src/pages/chat/chat.jsx
Labels: ✨ Feature

#146 [FEAT] 관리자페이지 가입 승인 연동
  src/apis/admin/getStudentVerificationsDetail.api.js
  src/apis/admin/getVerificationList.api.js
  src/apis/admin/postStudentVerifications.api.js
  src/components/common/ButtonRound.jsx
  src/components/layout/Admin.jsx
  src/constants/api.js
  src/pages/admin/SignupManagement.jsx
  src/pages/admin/board/BoardManagement.jsx
  src/pages/admin/signup/SignupManagement.jsx
  src/pages/admin/signup/StudentVerifications.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature

#151 [CHORE] 사소한 오류 해결, 기타 수정
  src/apis/home/getUniversity.api.js
  src/components/board/BoardListBox.jsx
  src/components/board/PostList.jsx
  src/components/board/TipsPostList.jsx
  src/components/board/write/WriteContent.jsx
  src/components/board/write/WriteTitle.jsx
  src/components/common/ScrapComponent.jsx
  src/components/home/BoardBox.jsx
  src/components/home/BoxList.jsx
  src/components/layout/Admin.jsx
  src/constants/api.js
  src/pages/admin/board/BoardManagement.jsx
  src/pages/admin/board/CreateBoard.jsx
  src/pages/admin/cardnews/CardnewsList.jsx
  src/pages/admin/cardnews/CreateCardnews.jsx
  src/pages/admin/notice/CreateNotice.jsx
  src/pages/admin/notice/NoticeManagement.jsx
  src/pages/admin/signup/SignupManagement.jsx
  src/pages/admin/signup/StudentVerifications.jsx
  src/pages/auth/schoolEmail.jsx
  src/pages/auth/schoolVerification.jsx
  src/pages/auth/terms.jsx
  src/pages/board/board.jsx
  src/pages/board/write.jsx
  src/pages/home/home.jsx
  src/pages/my/community/CommunityScrap.jsx
  src/pages/my/community/MyArticles.jsx
  src/pages/my/community/MyComments.jsx
  src/pages/my/community/scrap.jsx
  src/pages/my/mypage.jsx
  src/pages/my/service/notice/noticeDetail.jsx
  src/pages/my/settings/Notification.jsx
Labels: 🐛 Bug, ⚙️ Chore, 🎨 Design

#154 [FEAT] 댓글 번역 추가 및 번역 로직 수정
  src/apis/translate/translateText.api.js
  src/assets/imgs/translate.svg
  src/components/board/BoardListBox.jsx
  src/components/board/PostComment.jsx
  src/components/board/PostList.jsx
  src/components/common/TranslateButton.jsx
  src/constants/api.js
  src/hooks/useCommentTranslate.js
  src/hooks/usePostTranslate.js
  src/pages/board/post.jsx
  src/pages/home/home.jsx
  src/pages/my/settings/notification.jsx
Labels: ✨ Feature, ⚙️ Chore, ♻️ Refactor
