Repository IT-Cotato/10th-Kampus-FE, pull requests merged in 2025-04, with the labels that each got.

#158 [FEAT] 게시글 내 검색 및 검색 키워드 단일 삭제 및 전체 삭제 기능 구현
  src/apis/search/searchBoard.api.js
  src/apis/search/searchDeleteKeyword.api.js
  src/apis/search/searchTotal.api.js
  src/components/board/PostHeader.jsx
  src/components/search/RecentSearch.jsx
  src/components/search/SearchBar.jsx
  src/constants/api.js
  src/pages/search/Search.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature

#160 [FEAT] 대학명 영문으로 수정, 카테고리 동적 추가
  src/apis/auth/postSchoolPhoto.api.js
  src/apis/board/getBoardCategories.api.js
  src/components/board/write/SelectCategory.jsx
  src/components/join/searchDropdown.jsx
  src/constants/api.js
  src/constants/university.js
  src/pages/admin/board/CreateBoard.jsx
  src/pages/auth/schoolEmail.jsx
  src/pages/auth/schoolPhoto.jsx
  src/pages/auth/schoolSearch.jsx
  src/pages/board/write.jsx
  src/pages/home/home.jsx
  src/pages/my/mypage.jsx
  src/pages/my/settings/MyInfo.jsx
Labels: ✨ Feature

#165 [FEAT] 마이페이지 메일 연동 및 세세한 수정사항
  src/assets/imgs/activeScrap.svg
  src/assets/imgs/scrap.svg
  src/components/board/TipsPostList.jsx
  src/components/board/write/WriteTitle.jsx
  src/components/common/MainButton.jsx
  src/components/common/MainWhiteButton.jsx
  src/components/common/ScrapComponent.jsx
  src/components/layout/ContactUs.jsx
  src/constants/OfficialMail.json
  src/pages/admin/board/BoardManagement.jsx
  src/pages/board/post.jsx
  src/pages/board/write.jsx
  src/pages/my/mypage.jsx
  src/routes/AppRouter.jsx
  src/styles/global.css
  tailwind.config.js
Labels: ⚙️ Chore, 🎨 Design

#163 [Feat] 로그인 팝업, 계정 정지 관련 UI 생성
  jsconfig.json
  src/App.jsx
  src/assets/imgs/lock.svg
  src/assets/imgs/reportIcon.svg
  src/assets/imgs/unlock.svg
  src/components/block/accountSuspendedModal.jsx
  src/components/board/write/UploadPics.jsx
  src/components/chat/chatRoomPage.jsx
  src/components/common/Bubble.jsx
  src/components/common/ButtonRound.jsx
  src/components/common/Modal.jsx
  src/components/common/userInput.jsx
  src/components/layout/BlockingManagement.jsx
  src/components/layout/ContactUs.jsx
  src/components/layout/MyArticle.jsx
  src/components/layout/Scrap.jsx
  src/components/layout/layout.jsx
  src/pages/admin/signup/StudentVerifications.jsx
  src/pages/auth/login.jsx
  src/pages/home/accountPermanentSuspendedNotice.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: 🎨 Design, ♻️ Refactor

#169 fix: deploy
  src/components/chat/chatRoomPage.jsx
  src/components/common/userInput.jsx
Labels: 🐛 Bug
