Repository IT-Cotato/10th-Kampus-FE, pull requests merged in 2025-06, with the labels that each got.

#175 [FEAT] 관리자페이지 대시보드 구현
  package-lock.json
  src/apis/user/userDetail.api.js
  src/assets/imgs/admin/User.svg
  src/components/layout/Admin.jsx
  src/constants/api.js
  src/pages/admin/Dashboard.jsx
  src/pages/admin/Dashboard/Dashboard.jsx
  src/pages/index.js
  src/state/query/admin/useGetAdminUserData.js
Labels: ✨ Feature, 🎨 Design

#188 [FEAT] 카카오 로그인 방식 변경 및 인터셉터 구현
  package-lock.json
  package.json
  src/apis/auth/login.api.js
  src/apis/axios-instance.js
  src/apis/interceptor.js
  src/components/common/kakaoLogin.jsx
  src/constants/api.js
  src/pages/SplashScreen.jsx
  src/pages/auth/handler/KakaoLoginHandler.jsx
  src/pages/auth/login.jsx
  src/pages/index.js
  src/pages/my/mypage.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
  src/stores/useAuthStore.js
Labels: ✨ Feature, 🔨 Fix, ⚙️ Chore

#183 [Feat] 채팅 이미지, 채팅 타입 등 변동사항 수정, eslint 재설정
  eslint.config.js
  package-lock.json
  package.json
  src/apis/chat/chatList.api.js
  src/apis/chat/chatRoom.api.js
  src/apis/chat/messages.api.js
  src/assets/imgs/copied.svg
  src/components/chat/articleInfo.jsx
  src/components/chat/chatListPage.jsx
  src/components/chat/chatMenu.jsx
  src/components/chat/chatRoomPage.jsx
  src/components/chat/leaveModal.jsx
  src/components/chat/listItem.jsx
  src/components/chat/messageModal.jsx
  src/components/chat/roomHeader.jsx
  src/components/common/MenuBar.jsx
  src/components/common/userInput.jsx
  src/constants/api.js
  src/constants/boardConstant.js
  src/constants/chatType.js
  src/constants/inputType.js
  src/hooks/use-websocket.jsx
  src/pages/chat/chat.jsx
  src/state/mutation/chat/usePostChatroom.js
  src/state/query/chat/useGetChatList.js
  src/state/query/chat/useGetChatroom.js
  src/utils/formatTime.js
  src/utils/generateApiPath.js
  src/utils/utcToKst.js
Labels: ✨ Feature, 🔨 Fix
