Repository IT-Cotato/10th-Kampus-FE, pull requests merged in 2025-01, with the labels that each got.

#8 [FEAT] 구글 소셜 로그인 컴포넌트
  index.html
  src/apis/axios-instance.js
  src/components/common/googleLogin.jsx
  src/components/common/kakaoLogin.jsx
  src/pages/auth/login.jsx
  src/utils/authUtils.js
  vite.config.js
Labels: ✨ Feature

#10 [FEAT] 구글 소셜 로그인 구현
  .dist/.gitignore
  .dist/README.md
  .dist/package-lock.json
  .dist/package.json
  .dist/src/assets/icon/favicon.ico
  .dist/src/assets/imgs/logo.png
  .dist/src/css/style.css
  .dist/src/index.html
  .dist/src/js/capacitor-welcome.js
  .dist/src/manifest.json
  .dist/vite.config.ts
  .gitignore
  android/app/.gitignore
  android/app/build.gradle
  android/app/capacitor.build.gradle
  android/app/src/main/java/com/cotato/kampus/MainActivity.java
  android/capacitor.settings.gradle
  index.html
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App/AppDelegate.swift
  ios/App/App/GoogleService-Info.plist
  ios/App/App/Info.plist
  ios/App/Podfile
  ios/App/Podfile.lock
  package-lock.json
  package.json
  src/components/common/googleLogin.jsx
Labels: ✨ Feature

#13 [CHORE] tailwind 설정 파일 오타 수정 및 주석 추가
  tailwind.config.js
Labels: 🕶️ Style, ⚙️ Chore

#15 [FEAT] 회원가입 이용약관 동의
  package-lock.json
  package.json
  src/assets/imgs/check.svg
  src/assets/imgs/previous.svg
  src/assets/imgs/x.svg
  src/components/common/JoinInButton.jsx
  src/components/join/TermsModal.jsx
  src/components/join/term.jsx
  src/constants/detailedTerms.js
  src/pages/auth/terms.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/routes/path.ts
  tailwind.config.js
Labels: ✨ Feature, 🕶️ Style, ⚙️ Chore

#19 [FEAT] 마이페이지 contact us 퍼블리싱, 하단 navbar, 상단 title 뒤로가기
  src/assets/imgs/arrowLine.svg
  src/assets/imgs/navIcon/arrowLeft.svg
  src/assets/imgs/navIcon/board.svg
  src/assets/imgs/navIcon/boardActive.svg
  src/assets/imgs/navIcon/chat.svg
  src/assets/imgs/navIcon/chatActive.svg
  src/assets/imgs/navIcon/home.svg
  src/assets/imgs/navIcon/homeActive.svg
  src/assets/imgs/navIcon/market.svg
  src/assets/imgs/navIcon/marketActive.svg
  src/assets/imgs/navIcon/my.svg
  src/assets/imgs/navIcon/myActive.svg
  src/assets/index.js
  src/components/common/ButtonRound.jsx
  src/components/common/titleHeader.jsx
  src/components/layout/layout.jsx
  src/components/layout/navbar.jsx
  src/components/service/faq/faq.jsx
  src/components/service/faq/faqItem.jsx
  src/components/service/inquiry/inquiryButton.jsx
  src/components/service/inquiry/inquiryEmpty.jsx
  src/components/service/inquiry/inquiryItem.jsx
  src/components/service/inquiry/inquiryList.jsx
  src/components/service/notice.jsx
  src/pages/chat/list.jsx
  src/pages/my/mypage.jsx
  src/pages/my/service/inquiry.jsx
  src/pages/my/service/service.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
  src/styles/global.css
  tailwind.config.js
Labels: ⚙️ Chore

#24 [STYLE] navbar 컴포넌트 수정
  src/assets/imgs/navIcon/boardActive.svg
  src/assets/imgs/navIcon/chatActive.svg
  src/assets/imgs/navIcon/homeActive.svg
  src/assets/imgs/navIcon/marketActive.svg
  src/assets/imgs/navIcon/myActive.svg
  src/components/layout/layout.jsx
  src/components/layout/navbar.jsx
  tailwind.config.js
Labels: 🔨 Fix, 🕶️ Style

#25 [FIX] navbar 렌더링 오류 해결
  src/components/layout/layout.jsx
Labels: 🔨 Fix

#27 [FEAT] 일반 게시글 뷰 구현 및 board 라우팅 구현
  capacitor.config.json
  ios/App/App/Info.plist
  package-lock.json
  package.json
  src/assets/imgs/comment.svg
  src/assets/imgs/dropdown.svg
  src/assets/imgs/like.svg
  src/assets/imgs/menubar.svg
  src/assets/imgs/scrap.svg
  src/assets/imgs/translate.svg
  src/components/board/BoardList.jsx
  src/components/board/BoardListBox.jsx
  src/components/board/PinAniamte.jsx
  src/components/board/PostList.jsx
  src/components/common/DropBox.jsx
  src/pages/board/allboard.jsx
  src/pages/board/board.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  src/utils/boardTitleUtils.js
  tailwind.config.js
Labels: ✨ Feature, 🕶️ Style

#22 [FEAT] 회원가입 Profile Settings
  package-lock.json
  src/components/common/MainButton.jsx
  src/components/join/TermsModal.jsx
  src/components/join/searchDropdown.jsx
  src/components/join/usernameInput.jsx
  src/constants/languages.js
  src/constants/nations.js
  src/pages/auth/profileSettings.jsx
  src/pages/auth/terms.jsx
  src/pages/index.js
  src/routes/AppRouter.jsx
  tailwind.config.js
Labels: ✨ Feature, 🕶️ Style

#31 [FEAT] 마이페이지 구현
  src/assets/imgs/arrowRight.svg
  src/assets/imgs/notification.svg
  src/components/common/titleHeader.jsx
  src/components/common/toggle.jsx
  src/pages/index.js
  src/pages/my/community/myArticle.jsx
  src/pages/my/community/scrap.jsx
  src/pages/my/etc/blockingManagement.jsx
  src/pages/my/etc/deleteAccount.jsx
  src/pages/my/mypage.jsx
  src/pages/my/settings/myInfo.jsx
  src/pages/my/settings/notification.jsx
  src/pages/my/settings/schoolVerification.jsx
  src/routes/AppRouter.jsx
  src/routes/path.ts
Labels: ✨ Feature, 🕶️ Style, ⚙️ Chore
